# Generated by Django 4.2 on 2024-04-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='course',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='student',
            new_name='students',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='teachers',
            field=models.ManyToManyField(related_name='enrollments', to='api.teacher'),
        ),
    ]
